Updated native SDKs for iOS and Android
Azure/azure-mobile-engagement-unity pull request #4
Opened 2016-10-27 20:22 UTC by ogoguel

2016-11-02 15:15 UTC, iamclement requested changes
Just one small comment about the optional UserNotification framework.

2016-11-02 15:15 UTC, clpolet commented on src/EngagementPlugin/Editor/EngagementPostBuild.cs
> +			pbx.AddFrameworkToProject(targetUID,UNFramework,true);
Should be "false" here as the UserNotifications framework is optional, not used on devices running iOS < 10

2016-11-04 00:07 UTC, ogoguel commented
Done

2016-11-04 15:18 UTC, iamclement approved these changes

2016-11-04 15:18 UTC, merged